services:
  vue:
    image: my-vue-app
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: yarn run dev --host 0.0.0.0
    ports: 
      - "5175:5173"


  fastapi_api:
    image: my-fastapi-tool
    build:
      context: .
      dockerfile: ./docker/dockerfile.backend
    command: pdm app-start  ## TODO: do I need "pdm run"???
    ports: 
      - "8000:8080"
    depends_on:
      - db 
    environment:
      DB_USER: changxuan
      DB_PASSWORD: changxuan
      DB_DATABASE: postgres
      DB_HOST: db
      DB_PORT: 5432
      # USE_DOTENV: "True" ## TODO: do I need this line???
## docker compose build fastapi_api 
## COMMAND LINE for just run fastapi: docker compose run fastapi_api /bin/bash


  db:
    image: postgres
    restart: always
    shm_size: 128m
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: changxuan
      POSTGRES_PASSWORD: changxuan
      POSTGRES_DB: postgres